# Generated by Django 5.0.6 on 2024-06-11 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingAPI', '0002_alter_booking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='length',
            field=models.IntegerField(default=0),
        ),
    ]
