# Generated by Django 5.0.6 on 2024-06-11 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingAPI', '0003_alter_booking_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='stripe_checkout_id',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
