# Generated by Django 5.0.6 on 2024-06-11 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingAPI', '0004_alter_booking_stripe_checkout_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='stripe_checkout_id',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
