# Generated by Django 5.0.6 on 2024-07-09 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authAPI', '0007_initial'),
        ('bookingAPI', '0006_alter_booking_app_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='app_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authAPI.user'),
        ),
    ]
