# Generated by Django 5.0.6 on 2024-06-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authAPI', '0003_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='https://storage.googleapis.com/ix-blog-app/download.png', null=True, upload_to='static/profile-images'),
        ),
    ]
