# Generated by Django 5.0.6 on 2024-07-09 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authAPI', '0004_alter_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
    ]
