# Generated by Django 5.0.6 on 2024-07-09 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authAPI', '0005_remove_user_image'),
        ('bookingAPI', '0006_alter_booking_app_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
