# Generated by Django 5.0.6 on 2024-07-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authAPI', '0007_initial'),
        ('bookingAPI', '0007_alter_booking_app_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bookings',
            field=models.ManyToManyField(blank=True, related_name='users', to='bookingAPI.booking'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
