# Generated by Django 5.0.6 on 2024-07-25 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authAPI', '0008_user_bookings_user_is_active_user_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bookings',
        ),
    ]
